import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://192.168.12.26:5008/#/login")
    page.get_by_role("textbox", name="账号").click()
    page.get_by_role("textbox", name="账号").press("CapsLock")
    page.get_by_role("textbox", name="账号").fill("HYU")
    page.get_by_role("textbox", name="账号").press("Tab")
    page.get_by_role("textbox", name="密码").fill("123")
    page.get_by_role("textbox", name="账号").click()
    page.get_by_role("textbox", name="账号").fill("HY")
    page.get_by_role("button", name="登录").click()
    page.get_by_text("二楼").click()
    page.get_by_text("一楼").click()
    page.get_by_text("全部").click()
    page.locator("#el-id-6163-28").click()
    page.locator("#el-id-6163-28").press("CapsLock")
    page.locator("#el-id-6163-28").press("CapsLock")
    page.locator("#el-id-6163-28").fill("EE")
    page.locator("#el-id-6163-28").press("Enter")
    page.get_by_role("button", name="全屏展示").click()
    page.get_by_role("button", name="退出全屏").click()
    page.get_by_role("link", name="设备配置").click()
    page.get_by_role("button", name="注册设备").click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备分类$")).nth(4).click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备分类$")).nth(4).click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备型号$")).nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备型号$")).nth(4).click()
    page.get_by_role("textbox", name="设备位置码:").click()
    page.get_by_role("textbox", name="备注:").click()
    page.get_by_role("button", name="新增参数").click()
    page.get_by_role("link", name="删除").click()
    page.get_by_label("提示").get_by_role("button", name="确定").click()
    page.locator("#el-id-6163-92 span").nth(2).click()
    page.locator("label").filter(has_text=re.compile(r"^KVM$")).locator("span").nth(1).click()
    page.get_by_role("option", name="D5-12").click()
    page.get_by_role("button", name="确定").click()
    page.get_by_role("button", name="取消").click()
    page.get_by_role("textbox", name="设备型号").click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备状态$")).nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^请选择KVM/客户端$")).nth(4).click()
    page.get_by_role("option", name="KVM").click()
    page.locator("div").filter(has_text=re.compile(r"^秒$")).nth(2).click()
    page.get_by_role("button", name="搜索").click()
    page.locator("label").filter(has_text="设备在线自动检测").locator("span").nth(1).click()
    page.get_by_role("listitem", name="第 2 页").click()
    page.get_by_role("row", name="21 90A B2-7 B2-7 offline 2025").get_by_role("button").first.click()
    page.get_by_role("button", name="取消").click()
    page.get_by_role("row", name="21 90A B2-7 B2-7 offline 2025").get_by_role("button").nth(1).click()
    page.get_by_role("button", name="取消").click()
    page.get_by_role("row", name="21 90A B2-7 B2-7 offline 2025").get_by_role("button").nth(2).click()
    page.get_by_role("button", name="取消").click()
    page.get_by_role("link", name="设备类型").click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备分类$")).nth(4).click()
    page.get_by_role("option", name="测试仪").click()
    page.get_by_role("button", name="搜索").click()
    page.get_by_role("button", name="新增类型").click()
    page.locator("div").filter(has_text=re.compile(r"^请选择设备分类$")).nth(4).click()
    page.get_by_role("option", name="测试仪").click()
    page.get_by_role("textbox", name="* 设备型号:").click()
    page.get_by_role("textbox", name="* 设备型号:").fill("SCV66")
    page.get_by_role("textbox", name="设备厂家:").click()
    page.get_by_role("button", name="点击上传").click()
    page.get_by_role("button", name="点击上传").set_input_files("robotA.png")
    page.get_by_role("button", name="确定").click()
    page.get_by_role("row", name="1 测试仪 SCV66 编辑 删除").get_by_role("button").first.click()
    page.get_by_role("textbox", name="设备厂家:").click()
    page.get_by_role("textbox", name="设备厂家:").fill("tECG")
    page.get_by_role("button", name="确定").click()
    page.get_by_role("row", name="测试仪 SCV66 tECG 编辑 删除").get_by_role("button").nth(1).click()
    page.get_by_role("button", name="确认删除").click()
    page.get_by_role("link", name="KVM列表").click()
    page.get_by_role("textbox", name="KVM型号").click()
    page.get_by_text("请选择EAP绑定").click()
    page.get_by_role("option", name="已绑定").click()
    page.get_by_role("textbox", name="固件版本").click()
    page.get_by_role("textbox", name="KVM名称").click()
    page.get_by_role("button", name="搜索").click()
    page.get_by_role("button", name="编辑").nth(1).click()
    page.get_by_role("textbox", name="KVM型号:").click()
    page.get_by_role("textbox", name="KVM型号:").fill("ikas")
    page.get_by_role("button", name="确定").click()
    page.get_by_role("button", name="删除").first.click()
    page.get_by_role("button", name="确认删除").click()
    page.get_by_role("button", name="新增KVM").click()
    page.get_by_role("textbox", name="* KVM名称:").click()
    page.get_by_role("textbox", name="* KVM名称:").fill("Trimming-kvm")
    page.get_by_role("textbox", name="* KVM名称:").press("Tab")
    page.get_by_role("textbox", name="KVM型号:").fill("kvm01")
    page.get_by_role("textbox", name="KVM型号:").press("Tab")
    page.get_by_role("textbox", name="KVM MAC:").fill("")
    page.get_by_role("textbox", name="KVM MAC:").press("CapsLock")
    page.get_by_role("textbox", name="KVM MAC:").fill("DFADS34-234234")
    page.get_by_role("button", name="确定").click()
    page.get_by_role("link", name="设备布局").click()
    page.get_by_text("一楼").click()
    page.get_by_text("二楼").click()
    page.get_by_text("全部").click()
    page.get_by_role("button", name="配置显示信息").click()
    page.locator("div:nth-child(6) > .el-form-item > .el-form-item__content > .el-select > .el-select__wrapper > .el-select__selection > div:nth-child(2)").first.click()
    page.locator("div:nth-child(4) > .el-form-item > .el-form-item__content > .el-select > .el-select__wrapper > .el-select__selection > div:nth-child(2)").first.click()
    page.locator("div:nth-child(2) > .el-form-item").first.click()
    page.get_by_text("探针台*一层显示信息Prober").click()
    page.get_by_role("dialog", name="配置设备显示信息").click()
    page.get_by_label("配置设备显示信息").get_by_text("整批已测情况").nth(1).click()
    page.get_by_role("option", name="整批已测情况").click()
    page.locator("form:nth-child(4) > .el-row > div:nth-child(2) > .el-form-item > .el-form-item__content > .el-select > .el-select__wrapper > .el-select__selection > div:nth-child(2)").click()
    page.get_by_role("option", name="当前卡号").click()
    page.get_by_label("配置设备显示信息").get_by_text("当前卡号").nth(2).click()
    page.get_by_role("option", name="无").click()
    page.locator("div").filter(has_text=re.compile(r"^机台编号$")).nth(4).click()
    page.get_by_role("option", name="机台编号").click()
    page.locator("form:nth-child(4) > .el-row > div:nth-child(3) > .el-form-item > .el-form-item__content > .el-select > .el-select__wrapper").click()
    page.get_by_role("option", name="产品编号").click()
    page.locator("form:nth-child(4) > .el-row > div:nth-child(5)").click()
    page.get_by_role("option", name="客户批号").click()
    page.get_by_role("button", name="确定").click()
    page.get_by_role("link", name="设备资源表").click()
    page.get_by_text("请选择设备型号").click()
    page.get_by_role("option", name="9830").click()
    page.get_by_role("textbox", name="设备编号").click()
    page.get_by_role("button", name="搜索").click()
    page.locator("form path").nth(1).click()
    page.locator("form").get_by_role("img").first.click()
    page.get_by_role("button", name="搜索").click()
    page.locator(".el-table__body-wrapper > .el-scrollbar > div:nth-child(2) > .el-scrollbar__thumb").click()
    page.locator(".el-table__body-wrapper > .el-scrollbar > div:nth-child(2) > .el-scrollbar__thumb").click()
    page.get_by_text("操作").click()
    page.get_by_text("操作").click()
    page.get_by_role("row", name="1 90A A8-04 A5-4 A8-04 string").get_by_role("button").click()
    page.get_by_role("textbox", name="工步:").click()
    page.get_by_role("textbox", name="工步:").fill("CP1")
    page.get_by_role("button", name="确定").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
